const businessNames = [
  "Minhas Micro Brewery",
  "CK'S BBQ & Catering",
  "La Bastringue",
  "Geico Insurance",
  "Action Engine",
  "The Coffee Bean & Tea Leaf",
  "Bnc Cake House",
  "Thai One On",
  "Filiberto's Mexican Food",
  "Maggie & Stella's Gifts",
  "Sushi 8",
  "Southern Accent Restaurant",
  "Original Hamburger Works",
  "Mysore Indian Cuisine",
  "North Haven Barber Shop",
  "Safeway Food & Drug",
  "Harlow",
  "Citi Trends",
  "Nevada Title And Payday Loans",
  "CakesbyToi",
  "Park Stone Pavers",
  "Rally's Hamburgers",
  "Rib Shop",
  "Mabel's Bakery",
  "Salsitas",
  "Los Toros Numero 2",
  "ADT Security Services, Inc.",
  "The Coffee Mill Restaurant",
  "Laurier Optical",
  "Teresas Pizzeria",
  "Chicken Lips",
  "Schonheit Gardens",
  "Subway",
  "Omelet House Summerlin",
  "Pamper Me Perfect Beauty & Wellness",
  "Crossroads Country Cafe'",
  "Strickland's Ice Cream",
  "John John's Seafood",
  "Wellsprings of Gilbert",
  "Little Caesars Pizza",
  "Audio Express",
  "Dunkin Donuts",
  "Art Bathe",
  "Super 8 by Wyndham Toronto East ON",
  "Cinthya's Beauty Salon",
  "Aria Remodeling",
  "Kim Phat Inc",
  "Manuel's Mexican Restaurant & Cantina - Bell Rd",
  "GoodLife Fitness",
  "E R Automotive",
  "Not Just Antiques Mart",
  "Legislative Assembly of Ontario",
  "JAM Scooter Rental Of Las Vegas",
  "La Rosa Chilena",
  "Jia Jia International Moving",
  "Brett's Plumbing",
  "Crossfit Revitalize",
  "Junior's Pizzeria",
  "Shower Solutions",
  "Subway",
  "Baby Bundle 3d/4d Ultrasound",
  "Baja Fresh Mexican Grill",
  "Red Crowns Pub",
  "KD Nails",
  "Family Dentistry at CIC",
  "Chevron Pitstop",
  "Gold Pawn Brokers",
  "Philip Pelusi",
  "FedEx Office Print & Ship Center",
  "Royal Conservatory of Music",
  "On The Path Yard Care",
  "Central Church - Henderson",
  "Sunset Castle",
  "China Palace",
  "Blondie & Co Salon",
  "Mattress Firm South Euclid",
  "Marshalls",
  "Walgreens",
  "Lauren Byrne, MD",
  "Fit Life 120",
  "Allwyn's Bakery",
  "Mattress Firm Carefree",
  "Fornetti",
  "Provence Bakery",
  "Makeupbygaby1974",
  "Above and Beyond Dog Grooming",
  "Vegas Vapolife",
  "Ice Cream Patio",
  "Hub Coffee House & Locavorium",
  "Pizza Bellagio",
  "Long Animal Hospital",
  "Apple Nail & Spa",
  "Regino's Pizza",
  "Walmart",
  "Avenue Deli",
  "More Than Pies Baking",
  "Shoppers Drug Mart",
  "Indian Street Food Company",
  "Popular Nails",
  "Chase Bank"
]

module.exports = businessNames;